on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - id: backend-deployment
      uses: Zimboboys/express-deployment-aws@v0.1.0
      with:
        s3-bucket: 'oce-api-deployment'
        stack-name: 'oce-api-deployment-stack'
      env:
        CLIENT_URL: 'https://www.onecoolearth.h4i-cp.org/'
        SERVER_URL: 'https://2ht6f910k6.execute-api.us-west-1.amazonaws.com/prod'
        CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    - run: echo API is at ${{ steps.backend-deployment.outputs.api-url }}
      shell: bash
